### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by deadpyxel** [amirashabani/bain#1]
Came from reddit. Pretty neat idea, but I can't really tell what is missing to make the application work, so I think a README is in order.

That would help more people understand what to do.

**Comment by amirashabani** [comment]
Done. Thanks for reminding.
Let me know if there's anything wrong with instructions I put in the README section.

**Comment by amishbni** [comment]
@deadpyxel Done. Thanks for reminding.
Let me know if there's anything wrong with instructions I put in the README section.
